# Generated by Django 2.0.3 on 2018-03-21 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, default='', max_length=32)),
                ('carrier', models.CharField(blank=True, default='', max_length=50)),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=127)),
                ('mobile', models.CharField(blank=True, default='', max_length=11)),
                ('name', models.CharField(blank=True, default='', max_length=127)),
                ('homedir', models.CharField(blank=True, default='', max_length=255)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_account',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_account_profile',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_no', models.AutoField(primary_key=True, serialize=False)),
                ('family_id', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=127)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'healthplus_family',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='FamilyWeight',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('profile_id', models.IntegerField()),
                ('family_no', models.IntegerField()),
                ('weight', models.FloatField()),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'healthplus_family_weight',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('birthday', models.DateTimeField()),
                ('sex', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'health_member',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_no', models.IntegerField()),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('birth', models.IntegerField()),
                ('gender', models.SmallIntegerField(default=1)),
                ('height', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('secret', models.CharField(blank=True, default='', max_length=127)),
                ('secret_email', models.CharField(blank=True, default='', max_length=127)),
                ('secret_pw', models.CharField(blank=True, default='', max_length=127)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'healthplus_profile',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('birthday', models.DateTimeField(blank=True, default=None, null=True)),
                ('gender', models.SmallIntegerField(default=1)),
                ('height', models.IntegerField(blank=True, default=None, null=True)),
                ('image', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_profile',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('BFR', models.FloatField()),
                ('MMR', models.FloatField()),
                ('BD', models.FloatField()),
                ('legacy', models.SmallIntegerField()),
                ('mearsured', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weight',
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('member_id', models.CharField(blank=True, default='', max_length=32)),
                ('device_id', models.CharField(blank=True, default='', max_length=12)),
                ('device_sn', models.CharField(blank=True, default='', max_length=16)),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('pbf', models.FloatField()),
                ('wt_state', models.IntegerField()),
                ('resistance', models.IntegerField()),
                ('body_water', models.FloatField()),
                ('muscle', models.FloatField()),
                ('bone', models.FloatField()),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('utc', models.CharField(blank=True, default='', max_length=255)),
                ('userNo', models.IntegerField()),
                ('pbf_state', models.IntegerField()),
                ('basalMetabolism', models.FloatField()),
                ('visceralFatLevel', models.FloatField()),
            ],
            options={
                'db_table': 'health_weight_record',
                'ordering': ('created',),
            },
        ),
    ]
