# Generated by Django 2.0.3 on 2018-03-15 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(blank=True, default='', max_length=32)),
                ('carrier', models.CharField(blank=True, default='', max_length=50)),
                ('username', models.CharField(blank=True, default='', max_length=50)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(blank=True, default='', max_length=127)),
                ('mobile', models.CharField(blank=True, default='', max_length=11)),
                ('name', models.CharField(blank=True, default='', max_length=127)),
                ('homedir', models.CharField(blank=True, default='', max_length=255)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('value', models.CharField(blank=True, default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'account_profile',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Family',
            fields=[
                ('family_no', models.AutoField(primary_key=True, serialize=False)),
                ('family_id', models.CharField(blank=True, default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=127)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('family_name', models.CharField(blank=True, default='', max_length=50)),
                ('image', models.CharField(blank=True, default='', max_length=255)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'family',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='FamilyWeight',
            fields=[
                ('seq', models.AutoField(primary_key=True, serialize=False)),
                ('profile_id', models.IntegerField()),
                ('family_no', models.IntegerField()),
                ('weight', models.FloatField()),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'family_weight',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('birthday', models.DateTimeField()),
                ('sex', models.IntegerField()),
                ('deleted', models.BooleanField(default=False)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'member',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('family_no', models.IntegerField()),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('birth', models.IntegerField()),
                ('gender', models.SmallIntegerField(default=1)),
                ('height', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('secret', models.CharField(blank=True, default='', max_length=127)),
                ('secret_email', models.CharField(blank=True, default='', max_length=127)),
                ('secret_pw', models.CharField(blank=True, default='', max_length=127)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'profile',
                'ordering': ('created',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=100)),
                ('username', models.CharField(blank=True, default='', max_length=100)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('nickname', models.CharField(blank=True, default='', max_length=100)),
                ('birthday', models.DateTimeField(blank=True)),
                ('gender', models.SmallIntegerField(default=1)),
                ('height', models.IntegerField()),
                ('image', models.CharField(max_length=255)),
                ('state', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'users',
                'ordering': ('created',),
            },
        ),
    ]
