# Generated by Django 2.0.3 on 2018-03-22 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acc_id',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
