# Generated by Django 2.0.3 on 2018-03-15 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(blank=True, default='', max_length=100)),
                ('weight', models.FloatField()),
                ('BMI', models.FloatField()),
                ('BFR', models.FloatField()),
                ('MMR', models.FloatField()),
                ('BD', models.FloatField()),
                ('legacy', models.SmallIntegerField()),
                ('mearsured', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weight',
                'ordering': ('added',),
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default='', max_length=32)),
                ('member_id', models.CharField(blank=True, default='', max_length=32)),
                ('device_id', models.CharField(blank=True, default='', max_length=12)),
                ('device_sn', models.CharField(blank=True, default='', max_length=16)),
                ('measurement_date', models.DateTimeField(auto_now_add=True)),
                ('weight', models.FloatField()),
                ('bmi', models.FloatField()),
                ('pbf', models.FloatField()),
                ('wt_state', models.IntegerField()),
                ('resistance', models.IntegerField()),
                ('body_water', models.FloatField()),
                ('muscle', models.FloatField()),
                ('bone', models.FloatField()),
                ('remark', models.CharField(blank=True, default='', max_length=255)),
                ('deleted', models.BooleanField(default=False)),
                ('ts', models.BigIntegerField(blank=True)),
                ('client_id', models.CharField(blank=True, default='', max_length=32)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('utc', models.CharField(blank=True, default='', max_length=255)),
                ('userNo', models.IntegerField()),
                ('pbf_state', models.IntegerField()),
                ('basalMetabolism', models.FloatField()),
                ('visceralFatLevel', models.FloatField()),
            ],
            options={
                'db_table': 'weight_record',
                'ordering': ('created',),
            },
        ),
    ]
