# Generated by Django 2.0.3 on 2018-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_auto_20180322_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountprofile',
            name='profile_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
