# Generated by Django 2.0.3 on 2018-03-22 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0004_accountprofile_profile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='weight_record_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
