# Generated by Django 2.0.3 on 2018-03-22 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0005_auto_20180322_0346'),
    ]

    operations = [
        migrations.AddField(
            model_name='weight',
            name='BWR',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BD',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BFR',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BMI',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='MMR',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
