# Generated by Django 2.0.3 on 2018-03-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0007_auto_20180322_0402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weight',
            name='BD',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BFR',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BMI',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='BWR',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='MMR',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='weight',
            name='weight',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
    ]
