# Generated by Django 2.0.3 on 2018-03-23 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0008_auto_20180322_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weight',
            old_name='account',
            new_name='account_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='account',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='account_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name='weight',
            table='weights',
        ),
    ]
