# Generated by Django 2.0.3 on 2018-03-23 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0009_auto_20180323_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='family',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='familyweight',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
