# Generated by Django 2.0.3 on 2018-03-23 09:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0010_auto_20180323_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='account_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
