# Generated by Django 2.0.3 on 2018-03-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0011_auto_20180323_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
