# Generated by Django 2.0.3 on 2018-03-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0012_auto_20180323_1523'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownWeight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('weight', models.FloatField(blank=True, default=None, null=True)),
                ('BMI', models.FloatField(blank=True, default=None, null=True)),
                ('BFR', models.FloatField(blank=True, default=None, null=True)),
                ('BWR', models.FloatField(blank=True, default=None, null=True)),
                ('MMR', models.FloatField(blank=True, default=None, null=True)),
                ('BD', models.FloatField(blank=True, default=None, null=True)),
                ('legacy', models.SmallIntegerField()),
                ('measured', models.DateTimeField(auto_now_add=True)),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('device_id', models.CharField(blank=True, default=None, max_length=12, null=True)),
                ('device_sn', models.CharField(blank=True, default=None, max_length=16, null=True)),
            ],
            options={
                'db_table': 'unknowweights',
                'ordering': ('added', 'measured'),
            },
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.FloatField(default=None, null=True),
        ),
    ]
