# Generated by Django 2.0.3 on 2018-03-25 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0013_auto_20180324_1603'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UnknownWeight',
            new_name='WeightUnknown',
        ),
        migrations.AlterModelTable(
            name='weightunknown',
            table='weights_unknown',
        ),
    ]
