# Generated by Django 2.0.3 on 2018-04-05 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0016_auto_20180325_0838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightunknown',
            name='measured',
            field=models.DateTimeField(),
        ),
    ]
